[package]
name = "browser_snake"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
vector2d = "2.2.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true
panic = "abort"
